resultDir:
  '/public/home/liuzj/projects/singleCell/singleCellMouseNeuron/02_result/20210621/'
pipelineDir:
  '/public/home/liuzj/projects/singleCell/singleCellMouseNeuron/02_result/20210621/'
starIndex:
  '/public/home/liuzj/data/mm39/STAR_INDEX'
samples:
  allen_scRNA:
    sampleDir:
      '/public/home/liuzj/projects/singleCell/singleCellMouseNeuron/01_data/publicData/allen_scRNA/'
    expectedCell:
      5000
    umiLength:
      12
    whiteList:
      /public/home/liuzj/data/10xWhiteList/10xV3.txt
    includeIntron:
      False
  allen_snRNA:
    sampleDir:
      '/public/home/liuzj/projects/singleCell/singleCellMouseNeuron/01_data/publicData/allen_snRNA/'
    expectedCell:
      5000
    umiLength:
      12
    whiteList:
      /public/home/liuzj/data/10xWhiteList/10xV3.txt
    includeIntron:
      True
  cells_robert:
    sampleDir:
      '/public/home/liuzj/projects/singleCell/singleCellMouseNeuron/01_data/publicData/cells_robert/'
    expectedCell:
      5000
    umiLength:
      12
    whiteList:
      /public/home/liuzj/data/10xWhiteList/10xV3.txt
    includeIntron:
      True
  elife_prjna638719_placenta:
    sampleDir:
      '/public/home/liuzj/projects/singleCell/singleCellMouseNeuron/01_data/publicData/elife_prjna638719_placenta/'
    expectedCell:
      5000
    umiLength:
      12
    whiteList:
      /public/home/liuzj/data/10xWhiteList/10xV3.txt
    includeIntron:
      True
  GSM5111192_Cervical:
    sampleDir:
      '/public/home/liuzj/projects/singleCell/singleCellMouseNeuron/01_data/publicData/GSM5111192_Cervical/'
    expectedCell:
      5000
    umiLength:
      12
    whiteList:
      /public/home/liuzj/data/10xWhiteList/10xV3.txt
    includeIntron:
      True
  nmGSM5077288_DVC_v2:
    sampleDir:
      '/public/home/liuzj/projects/singleCell/singleCellMouseNeuron/01_data/publicData/nmGSM5077288_DVC_v2/'
    expectedCell:
      5000
    umiLength:
      10
    whiteList:
      /public/home/liuzj/data/10xWhiteList/10xV2.txt
    includeIntron:
      True
  songNew:
    sampleDir:
      '/public/home/liuzj/projects/singleCell/singleCellMouseNeuron/01_data/publicData/songNew/'
    expectedCell:
      5000
    umiLength:
      12
    whiteList:
      /public/home/liuzj/data/10xWhiteList/10xV3.txt
    includeIntron:
      True
  songOld:
    sampleDir:
      '/public/home/liuzj/projects/singleCell/singleCellMouseNeuron/01_data/publicData/songOld/'
    expectedCell:
      5000
    umiLength:
      12
    whiteList:
      /public/home/liuzj/data/10xWhiteList/10xV3.txt
    includeIntron:
      True
  SRR11688494_striatal_v2:
    sampleDir:
      '/public/home/liuzj/projects/singleCell/singleCellMouseNeuron/01_data/publicData/SRR11688494_striatal_v2/'
    expectedCell:
      5000
    umiLength:
      10
    whiteList:
      /public/home/liuzj/data/10xWhiteList/10xV2.txt
    includeIntron:
      True
  SRR9895509_medialPrefrontalCortex:
    sampleDir:
      '/public/home/liuzj/projects/singleCell/singleCellMouseNeuron/01_data/publicData/SRR9895509_medialPrefrontalCortex/'
    expectedCell:
      5000
    umiLength:
      12
    whiteList:
      /public/home/liuzj/data/10xWhiteList/10xV3.txt
    includeIntron:
      True

