pipelineDir:
  "/public/home/liuzj/publicPipeline/snuupy/"
combineScriptDir:
  '/public/home/liuzj/scripts/pipeline/combineSnuupyAndSiceloreResult/scripts/'
resultDir:
  "/public/home/liuzj/shortcuts/singleCellEndosperm/combinedNanopore/"
rawNanoporeFa:
  "/public/home/liuzj/projects/singleCellEndosperm/00_data/rawNanoporeData/allEndo.fasta"
nanoporeWorkspace:
  '/public/home/liuzj/projects/singleCellEndosperm/00_data/rawNanoporeData/workspace/'
nanoporeSeqSummary:
  '/public/home/liuzj/projects/singleCellEndosperm/00_data/rawNanoporeData/sequencing_summary.txt'

siceloreBam:
  "/public/home/liuzj/projects/singleCellEndosperm/01_results/sicelore/results/step6_tagBarcodeUmi/addBarcodeUmi_umifound_.bam"
siceloreFasta:
  "/public/home/liuzj/projects/singleCellEndosperm/01_results/sicelore/results/step7_computeConsensusSeq/allConsensus.fa"
snuupyFea:
  "/public/home/liuzj/projects/singleCellEndosperm/01_results/cellRanger/step9_barcodeAssignment/nanoporeAssigned.feather"
snuupyFasta:
  "/public/home/liuzj/projects/singleCellEndosperm/01_results/cellRanger/step10_polishReads/polishedReads.fa"
cellRangerH5:
  "/public/home/liuzj/projects/singleCellEndosperm/01_results/cellRanger/step1_runCellRanger/test/outs/filtered_feature_bc_matrix.h5"

#genome files
geneAnnoBed:
  '/public/home/liuzj/publicPipeline/snuupy/example/00_data/ref/annoFile/gene.bed'
geneAnnoRepreBed:
  '/public/home/liuzj/publicPipeline/snuupy/example/00_data/ref/annoFile/araport11.representative.gene_model.bed'
geneNot12Bed:
  '/public/home/liuzj/publicPipeline/snuupy/example/00_data/ref/annoFile/geneNotBed12.bed'
genomeFa:
  '/public/home/liuzj/publicPipeline/snuupy/example/00_data/ref/annoFile/genome.fa'
genomeFai:
  '/public/home/liuzj/publicPipeline/snuupy/example/00_data/ref/annoFile/genome.fa.fai'
usedIntron:
  '/public/home/liuzj/publicPipeline/snuupy/example/00_data/ref/annoFile/select_intron_by_Cyto.id.txt'

#softwares path
minimap2Path:
  '/public/home/liuzj/softwares/anaconda3/bin/minimap2'
picardPath:
  '/public/home/liuzj/softwares/picard/picard.jar'
seqkitPath:
  '/public/home/liuzj/softwares/anaconda3/bin/seqkit'
blastPath:
  '/public/home/liuzj/softwares/blast/ncbi-blast-2.10.0+/bin/'
poaPath:
  '/public/home/liuzj/softwares/poaV2/poa'
raconPath:
  '/public/home/liuzj/softwares/racon/build/bin/racon'
penaltyMatPath:
  '/public/home/liuzj/publicPipeline/snuupy/example/00_data/ref/blosum80.mat'
bedtoolsPath:
  '/public/home/liuzj/softwares/anaconda3/bin/bedtools'