resultDir:
  '/public/home/liuzj/projects/singleCell/clock/03_result/PRJNA742744/'
pipelineDir:
  '/public/home/liuzj/projects/singleCell/clock/03_result/PRJNA742744/'
starIndex:
  '/public/home/liuzj/data/Araport11/STAR_INDEX'
samples:
  ED1:
    dir_fastq:
      '/public/home/liuzj/projects/singleCell/clock/01_data/PRJNA742744/fastq/'
    r1:
      'ED1_S1_L001_R1_001.fastq.gz,ED1_S2_L001_R1_001.fastq.gz'
    r2:
      'ED1_S1_L001_R2_001.fastq.gz,ED1_S2_L001_R2_001.fastq.gz'
    expectedCell:
      5000
    umiLength:
      8
    umiStart:
      13
    cbLength:
      12
    cbStart:
      1
    r1Length:
      150 
    includeIntron:
      True
  ED2:
    dir_fastq:
      '/public/home/liuzj/projects/singleCell/clock/01_data/PRJNA742744/fastq/'
    r1:
      'ED2_S1_L001_R1_001.fastq.gz,ED2_S2_L001_R1_001.fastq.gz'
    r2:
      'ED2_S1_L001_R2_001.fastq.gz,ED2_S2_L001_R2_001.fastq.gz'
    expectedCell:
      5000
    umiLength:
      8
    umiStart:
      13
    cbLength:
      12
    cbStart:
      1
    r1Length:
      150 
    includeIntron:
      True
  ED3:
    dir_fastq:
      '/public/home/liuzj/projects/singleCell/clock/01_data/PRJNA742744/fastq/'
    r1:
      'ED3_S1_L001_R1_001.fastq.gz,ED3_S2_L001_R1_001.fastq.gz'
    r2:
      'ED3_S1_L001_R2_001.fastq.gz,ED3_S2_L001_R2_001.fastq.gz'
    expectedCell:
      5000
    umiLength:
      8
    umiStart:
      13
    cbLength:
      12
    cbStart:
      1
    r1Length:
      150 
    includeIntron:
      True
  EN1:
    dir_fastq:
      '/public/home/liuzj/projects/singleCell/clock/01_data/PRJNA742744/fastq/'
    r1:
      'EN1_S1_L001_R1_001.fastq.gz,EN1_S1_L001_R1_001.fastq.gz'
    r2:
      'EN1_S1_L001_R1_001.fastq.gz,EN1_S2_L001_R1_001.fastq.gz'
    expectedCell:
      5000
    umiLength:
      8
    umiStart:
      13
    cbLength:
      12
    cbStart:
      1
    r1Length:
      150 
    includeIntron:
      True
  EN2:
    dir_fastq:
      '/public/home/liuzj/projects/singleCell/clock/01_data/PRJNA742744/fastq/'
    r1:
      'EN2_S1_L001_R1_001.fastq.gz,EN2_S1_L001_R1_001.fastq.gz'
    r2:
      'EN2_S1_L001_R1_001.fastq.gz,EN2_S2_L001_R1_001.fastq.gz'
    expectedCell:
      5000
    umiLength:
      8
    umiStart:
      13
    cbLength:
      12
    cbStart:
      1
    r1Length:
      150 
    includeIntron:
      True
  EN3:
    dir_fastq:
      '/public/home/liuzj/projects/singleCell/clock/01_data/PRJNA742744/fastq/'
    r1:
      'EN3_S1_L001_R1_001.fastq.gz,EN3_S1_L001_R1_001.fastq.gz'
    r2:
      'EN3_S1_L001_R1_001.fastq.gz,EN3_S2_L001_R1_001.fastq.gz'
    expectedCell:
      5000
    umiLength:
      8
    umiStart:
      13
    cbLength:
      12
    cbStart:
      1
    r1Length:
      150 
    includeIntron:
      True